name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DB_DATABASE: test
      DB_HOST: test
      DB_USERNAME: root
      DB_PASSWORD: test

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up
