name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create .env file
      run: |
          echo "create .env file"
          touch .env
          echo MYSQL_ROOT_PASSWORD: root >> .env
          echo DB_DATABASE: test >> .env
          echo DB_HOST: test >> .env
          echo DB_USERNAME: root >> .env
          echo DB_PASSWORD: test >> .env
          echo "cat .env"
          cat .env
    - name: Build the Docker image
      run: docker-compose up -d
